#!/bin/csh -f
# RAMIC Bridge 配置文件生成脚本
# Generate virtuoso_setup.il for RAMIC Bridge
# 作者: AMS-IO-Agent Team
# 版本: 1.0.0

# 设置错误时退出
set exit_on_error

# 日志函数
alias print_info 'echo "[INFO]" \!*'
alias print_success 'echo "[SUCCESS]" \!*'
alias print_error 'echo "[ERROR]" \!*'

# 获取项目根目录（脚本在 setup/ 子目录中）
set CURPWD = `pwd`
set SCRIPT_DIR = `dirname $0`

# 获取脚本所在目录的绝对路径
if ("$SCRIPT_DIR" == ".") then
    set SCRIPT_ABS = "$CURPWD"
else
    cd $SCRIPT_DIR
    set SCRIPT_ABS = "`pwd`"
    cd $CURPWD
endif

# 项目根目录是脚本目录的上一级（因为脚本在 setup/ 中）
cd "$SCRIPT_ABS/.."
set PROJECT_ROOT = "`pwd`"
cd $CURPWD

# 主函数
main:
    cd "$PROJECT_ROOT"
    
    # 定义输出文件路径
    set OUTPUT_FILE = "setup/virtuoso_setup.il"
    set OUTPUT_FULL_PATH = "$PROJECT_ROOT/$OUTPUT_FILE"
    
    # 检查 RAMIC Bridge 文件是否存在
    if (! -f "src/tools/ramic_bridge/ramic_bridge.il") then
        print_error "[RAMIC] 未找到 ramic_bridge.il"
        exit 1
    endif
    
    # 生成 virtuoso_setup.il（英文版）到 setup 目录
    echo "; Virtuoso CIW Setup Script - RAMIC Bridge" > $OUTPUT_FILE
    echo "; Auto-generated by generate_virtuoso_ramicbridge.csh" >> $OUTPUT_FILE
    /bin/echo '; Execute in CIW: load("'$OUTPUT_FULL_PATH'")' >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "; Set environment variable" >> $OUTPUT_FILE
    /bin/printf 'setShellEnvVar("RB_DAEMON_PATH" "%s")\n' "$PROJECT_ROOT/src/tools/ramic_bridge/ramic_bridge_daemon_27.py" >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "; Load RAMIC Bridge IL script" >> $OUTPUT_FILE
    /bin/printf 'load("%s")\n' "$PROJECT_ROOT/src/tools/ramic_bridge/ramic_bridge.il" >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "; Load screenshot script" >> $OUTPUT_FILE
    /bin/printf 'load("%s")\n' "$PROJECT_ROOT/skill_tools/screenshot_complete.il" >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "; Setup complete! Ensure USE_RAMIC_BRIDGE=true in .env" >> $OUTPUT_FILE
    
    # 更新 .env 文件
    if (-f ".env") then
        grep -q "USE_RAMIC_BRIDGE" .env
        if ($status == 0) then
            sed -i 's/USE_RAMIC_BRIDGE=.*/USE_RAMIC_BRIDGE=true/' .env
        endif
    endif
    
    print_success "[RAMIC] virtuoso_setup.il 已生成: $OUTPUT_FULL_PATH [.env: USE_RAMIC_BRIDGE=true]"
    echo ""
    /bin/echo '[下一步][在 CIW 中执行] load("'$OUTPUT_FULL_PATH'")' 
    echo "[下一步][跨服务器连接] ssh -N -L 65432:127.0.0.1:65432 user@virtuoso-server"
    echo ""
    exit 0

# 运行主函数
goto main