#!/bin/csh -f
# Generate virtuoso_setup.il for RAMIC Bridge
# Author: AMS-IO-Agent Team
# Version: 1.0.0

# Exit on error
set exit_on_error

# Logging functions
alias print_info 'echo "[INFO]" \!*'
alias print_success 'echo "[SUCCESS]" \!*'
alias print_error 'echo "[ERROR]" \!*'

# Get project root directory (script is in setup/ subdirectory)
set CURPWD = `pwd`
set SCRIPT_DIR = `dirname $0`

# Get absolute path of script directory
if ("$SCRIPT_DIR" == ".") then
    set SCRIPT_ABS = "$CURPWD"
else
    cd $SCRIPT_DIR
    set SCRIPT_ABS = "`pwd`"
    cd $CURPWD
endif

# Project root is parent of script directory (since script is in setup/)
cd "$SCRIPT_ABS/.."
set PROJECT_ROOT = "`pwd`"
cd $CURPWD

# 主函数
main:
    cd "$PROJECT_ROOT"
    
    # Define output file path (in project root)
    set OUTPUT_FILE = "virtuoso_setup.il"
    set OUTPUT_FULL_PATH = "$PROJECT_ROOT/$OUTPUT_FILE"
    
    # Check if RAMIC Bridge file exists
    if (! -f "src/scripts/ramic_bridge/ramic_bridge.il") then
        print_error "[RAMIC] ramic_bridge.il not found at: src/scripts/ramic_bridge/ramic_bridge.il"
        print_info "[RAMIC] This file is required for RAMIC Bridge setup"
        print_info "[RAMIC] Please ensure the file exists or use skillbridge instead (set bridge_choice = 2 in setup.csh)"
        exit 1
    endif
    
    # Generate virtuoso_setup.il to setup directory
    echo "; Virtuoso CIW Setup Script - RAMIC Bridge" > $OUTPUT_FILE
    echo "; Auto-generated by generate_virtuoso_ramicbridge.csh" >> $OUTPUT_FILE
    /bin/echo '; Execute in CIW: load("'$OUTPUT_FULL_PATH'")' >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "; Set environment variable" >> $OUTPUT_FILE
    /bin/printf 'setShellEnvVar("RB_DAEMON_PATH" "%s")\n' "$PROJECT_ROOT/src/scripts/ramic_bridge/ramic_bridge_daemon_27.py" >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "; Load RAMIC Bridge IL script" >> $OUTPUT_FILE
    /bin/printf 'load("%s")\n' "$PROJECT_ROOT/src/scripts/ramic_bridge/ramic_bridge.il" >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "; Load screenshot script" >> $OUTPUT_FILE
    /bin/printf 'load("%s")\n' "$PROJECT_ROOT/src/skill/screenshot_complete.il" >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "; Setup complete! Ensure USE_RAMIC_BRIDGE=true in .env" >> $OUTPUT_FILE
    
    # 更新 .env 文件
    if (-f ".env") then
        grep -q "USE_RAMIC_BRIDGE" .env
        if ($status == 0) then
            sed -i 's/USE_RAMIC_BRIDGE=.*/USE_RAMIC_BRIDGE=true/' .env
        endif
    endif
    
    print_success "[RAMIC] virtuoso_setup.il generated: $OUTPUT_FULL_PATH [.env: USE_RAMIC_BRIDGE=true]"
    exit 0

# Run main function
goto main