#!/bin/csh -f
# Generate .env Configuration File Script
# 作者: AMS-IO-Agent Team
# 版本: 2.0.0

# 设置错误时退出
set exit_on_error

# 日志函数
alias print_info 'echo "[INFO]" \!*'

# 获取项目根目录（脚本在 setup/ 子目录中）
set CURPWD = `pwd`
set SCRIPT_DIR = `dirname $0`

# 获取脚本所在目录的绝对路径
if ("$SCRIPT_DIR" == ".") then
    set SCRIPT_ABS = "$CURPWD"
else
    cd $SCRIPT_DIR
    set SCRIPT_ABS = "`pwd`"
    cd $CURPWD
endif

# 项目根目录是脚本目录的上一级（因为脚本在 setup/ 中）
cd "$SCRIPT_ABS/.."
set PROJECT_ROOT = "`pwd`"
cd $CURPWD

# 主函数
main: 
    # 切换到项目根目录
    cd "$PROJECT_ROOT"
    print_info "项目根目录: $PROJECT_ROOT"
    
    # 检查 .env 文件是否已存在
    if (-f ".env") then
        print_info "主要配置文件 [.env] 已存在，覆盖"
        if (-f ".env.backup") then
            print_info "备份配置文件 [.env.backup] 已存在，不覆盖"
        else
            print_info "备份配置文件为 [.env.backup]"
            cp .env .env.backup
        endif
    endif
    
    goto create_env_file

# 创建 .env 文件
create_env_file:
    # 设置默认 CDS 路径
    set default_cds = "$HOME/TSMC28/TEST/cds.lib"
    set default_cds180 = "$HOME/TSMC180/TEST/cds.lib"
    
    # 生成 .env 文件（使用 ASCII 字符避免编码问题）
    echo "# ================================================" > .env
    echo "# AMS-IO-Agent Environment Configuration" >> .env
    echo "# Auto-generated by generate_env_config.csh" >> .env
    echo "# ================================================" >> .env
    echo "" >> .env
    echo "# Replace with your actual API keys" >> .env
    echo "DEEPSEEK_API_KEY=your_deepseek_api_key_here" >> .env
    echo "WANDOU_API_KEY=your_wandou_api_key_here" >> .env
    echo "" >> .env
    echo "# Virtuoso Bridge Selection (true/1/yes to enable RAMIC Bridge, otherwise use skillbridge)" >> .env
    echo "USE_RAMIC_BRIDGE=true" >> .env
    echo "" >> .env
    echo "# RAMIC Bridge Connection (only used when RAMIC Bridge is enabled)" >> .env
    echo "RB_HOST=127.0.0.1" >> .env
    echo "RB_PORT=65432" >> .env
    echo "" >> .env
    echo "# CDS Library Paths (Modify these paths according to your environment)" >> .env
    echo "CDS_LIB_PATH=$default_cds" >> .env
    echo "CDS_LIB_PATH_180=$default_cds180" >> .env
    echo "" >> .env
    echo "# Logging Configuration" >> .env
    echo "ENABLE_LOGGING=true" >> .env
    echo "LOG_LEVEL=INFO" >> .env
    echo "" >> .env
    echo "# User Profile Configuration" >> .env
    echo "# Path to user profile markdown file (relative to project root)" >> .env
    echo "USER_PROFILE_PATH=user_data/default_user_profile.md" >> .env
    echo "# Set to empty or 'none' to disable user profile loading" >> .env
    echo "# USER_PROFILE_PATH=" >> .env
    
    # 显示配置摘要
    echo ""
    print_info "配置文件已生成: [$PROJECT_ROOT/.env]，请修改以下配置："
    echo "  • DEEPSEEK_API_KEY / WANDOU_API_KEY - API 密钥"
    echo "  • USE_RAMIC_BRIDGE - Bridge 类型 (true=跨服务器, false=同服务器)"
    echo "  • CDS_LIB_PATH (28nm) - 默认: $default_cds"
    echo "  • CDS_LIB_PATH_180 (180nm) - 默认: $default_cds180"
    echo ""
    exit 0

# 运行主函数
goto main