#!/bin/csh -f
# Generate virtuoso_setup.il for skillbridge
# Author: AMS-IO-Agent Team
# Version: 1.0.0

# Exit on error
set exit_on_error

# Logging functions
alias print_info 'echo "[INFO]" \!*'
alias print_success 'echo "[SUCCESS]" \!*'
alias print_error 'echo "[ERROR]" \!*'

# Get project root directory (script is in setup/ subdirectory)
set CURPWD = `pwd`
set SCRIPT_DIR = `dirname $0`

# Get absolute path of script directory
if ("$SCRIPT_DIR" == ".") then
    set SCRIPT_ABS = "$CURPWD"
else
    cd $SCRIPT_DIR
    set SCRIPT_ABS = "`pwd`"
    cd $CURPWD
endif

# Project root is parent of script directory (since script is in setup/)
cd "$SCRIPT_ABS/.."
set PROJECT_ROOT = "`pwd`"
cd $CURPWD

# 主函数
main:
    cd "$PROJECT_ROOT"
    
    # Define output file path (in project root)
    set OUTPUT_FILE = "virtuoso_setup.il"
    set OUTPUT_FULL_PATH = "$PROJECT_ROOT/$OUTPUT_FILE"
    
    # Get skillbridge path (from virtual environment)
    if (! -f ".venv/bin/skillbridge") then
        print_error "[skillbridge] Not installed in virtual environment [Please run: pip install skillbridge]"
        exit 1
    endif
    
    # Use skillbridge from virtual environment
    .venv/bin/skillbridge path >& /tmp/skillbridge_path.tmp
    set SKILLBRIDGE_PATH = `grep "python_server.il" /tmp/skillbridge_path.tmp | head -1`
    rm -f /tmp/skillbridge_path.tmp
    
    # 验证路径
    if ("$SKILLBRIDGE_PATH" == "") then
        print_error "[skillbridge] 无法获取路径"
        exit 1
    endif
    
    # 生成 virtuoso_setup.il（英文版）到 setup 目录
    echo "; Virtuoso CIW Setup Script - skillbridge" > $OUTPUT_FILE
    echo "; Auto-generated by generate_virtuoso_skillbridge.csh" >> $OUTPUT_FILE
    /bin/echo '; Execute in CIW: load("'$OUTPUT_FULL_PATH'")' >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "; Load skillbridge server script" >> $OUTPUT_FILE
    /bin/printf 'load("%s")\n' "$SKILLBRIDGE_PATH" >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "; Load screenshot script" >> $OUTPUT_FILE
    /bin/printf 'load("%s")\n' "$PROJECT_ROOT/src/skill/screenshot_complete.il" >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "; Start Python server" >> $OUTPUT_FILE
    echo "pyStartServer" >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "; Setup complete! Ensure USE_RAMIC_BRIDGE=false in .env" >> $OUTPUT_FILE
    
    # Update .env file
    if (-f ".env") then
        grep -q "USE_RAMIC_BRIDGE" .env
        if ($status == 0) then
            sed -i 's/USE_RAMIC_BRIDGE=.*/USE_RAMIC_BRIDGE=false/' .env
        endif
    endif
    
    print_success "[skillbridge] virtuoso_setup.il generated: $OUTPUT_FULL_PATH [.env: USE_RAMIC_BRIDGE=false]"
    exit 0

# Run main function
goto main

