#!/bin/csh -f
# Generate .env Configuration File Script
# Author: AMS-IO-Agent Team
# Version: 2.0.0

# Exit on error
set exit_on_error

# Logging function
alias print_info 'echo "[INFO]" \!*'

# Get project root directory (script is in setup/ subdirectory)
set CURPWD = `pwd`
set SCRIPT_DIR = `dirname $0`

# Get absolute path of script directory
if ("$SCRIPT_DIR" == ".") then
    set SCRIPT_ABS = "$CURPWD"
else
    cd $SCRIPT_DIR
    set SCRIPT_ABS = "`pwd`"
    cd $CURPWD
endif

# Project root is parent of script directory (since script is in setup/)
cd "$SCRIPT_ABS/.."
set PROJECT_ROOT = "`pwd`"
cd $CURPWD

# Main function
main: 
    # Switch to project root directory
    cd "$PROJECT_ROOT"
    print_info "Project root: $PROJECT_ROOT"
    
    # Check if .env file already exists
    if (-f ".env") then
        print_info "Main configuration file [.env] already exists, overwriting"
        print_info "Backing up current configuration file to [.env.backup]"
            cp .env .env.backup
    endif
    
    goto create_env_file

# Create .env file
create_env_file:
    # Set default CDS paths
    set default_cds = "$HOME/TSMC28/TEST/cds.lib"
    set default_cds180 = "$HOME/TSMC180/TEST/cds.lib"
    
    # Generate .env file (using ASCII characters to avoid encoding issues)
    echo "# ================================================" > .env
    echo "# AMS-IO-Agent Environment Configuration" >> .env
    echo "# Auto-generated by generate_env_config.csh" >> .env
    echo "# ================================================" >> .env
    echo "" >> .env
    echo "# ================================================" >> .env
    echo "# MODEL CONFIGURATION" >> .env
    echo "# ================================================" >> .env
    echo "# To add a model, configure these three variables:" >> .env
    echo "#   MODELNAME_API_BASE=https://api.provider.com/v1" >> .env
    echo "#   MODELNAME_MODEL_ID=model-id" >> .env
    echo "#   MODELNAME_API_KEY=your_api_key_here" >> .env
    echo "#" >> .env
    echo "# Example: DeepSeek (default, uncomment to use)" >> .env
    echo "" >> .env
    echo "# DeepSeek" >> .env
    echo "DEEPSEEK_API_BASE=https://api.deepseek.com/v1" >> .env
    echo "DEEPSEEK_MODEL_ID=deepseek-chat" >> .env
    echo "DEEPSEEK_API_KEY=your_deepseek_api_key_here" >> .env
    echo "" >> .env
    echo "# Virtuoso Bridge Selection (true/1/yes to enable RAMIC Bridge, otherwise use skillbridge)" >> .env
    echo "USE_RAMIC_BRIDGE=true" >> .env
    echo "" >> .env
    echo "# RAMIC Bridge Connection (only used when RAMIC Bridge is enabled)" >> .env
    echo "RB_HOST=127.0.0.1" >> .env
    echo "RB_PORT=65432" >> .env
    echo "" >> .env
    echo "# CDS Library Paths (Modify these paths according to your environment)" >> .env
    echo "CDS_LIB_PATH=$default_cds" >> .env
    echo "CDS_LIB_PATH_180=$default_cds180" >> .env
    echo "" >> .env
    echo "# Logging Configuration" >> .env
    echo "ENABLE_LOGGING=true" >> .env
    echo "LOG_LEVEL=INFO" >> .env
    echo "" >> .env
    echo "# User Profile Configuration" >> .env
    echo "# Path to user profile markdown file (relative to project root)" >> .env
    echo "USER_PROFILE_PATH=user_data/default_user_profile.md" >> .env
    echo "# Set to empty or 'none' to disable user profile loading" >> .env
    echo "# USER_PROFILE_PATH=" >> .env
    
    # Display configuration summary
    echo ""
    print_info "Configuration file generated: [$PROJECT_ROOT/.env], please modify the following:"
    echo "  • DEEPSEEK_API_KEY / WANDOU_API_KEY - API keys"
    echo "  • USE_RAMIC_BRIDGE - Bridge type (true=cross-server, false=same-server)"
    echo "  • CDS_LIB_PATH (28nm) - Default: $default_cds"
    echo "  • CDS_LIB_PATH_180 (180nm) - Default: $default_cds180"
    echo ""
    exit 0

# Run main function
goto main