@echo off
REM ================================================
REM AMS-IO-Agent Auto Setup Script (Windows CMD)
REM Version: 2.0.0
REM ================================================

setlocal enabledelayedexpansion

REM Get project root directory
set "SCRIPT_DIR=%~dp0"
cd /d "%SCRIPT_DIR%.."
set "PROJECT_ROOT=%cd%"

echo.
echo =================================
echo   AMS-IO-Agent Auto Setup Script
echo   Windows CMD Edition
echo   v2.0.0
echo =================================
echo.

echo [INFO] Project Root: %PROJECT_ROOT%

REM ================================================
REM Step 1: Check Requirements
REM ================================================
echo.
echo [INFO] [1/5] Checking system requirements...

REM Check Git
git --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Git is not installed. Please install Git first.
    echo Download from: https://git-scm.com/download/win
    exit /b 1
)
echo [INFO] Git found

REM Check Python
python --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed. Please install Python 3.11+ first.
    echo Download from: https://www.python.org/downloads/
    exit /b 1
)
echo [INFO] Python found

echo [SUCCESS] System check passed

REM ================================================
REM Step 2: Install uv
REM ================================================
echo.
echo [INFO] [2/5] Setting up uv package manager...

uv --version >nul 2>&1
if errorlevel 1 (
    echo [INFO] uv not found, installing via pip...
    pip install uv
    if errorlevel 1 (
        echo [ERROR] Failed to install uv
        echo Please install manually: pip install uv
        exit /b 1
    )
)
echo [SUCCESS] uv is available

REM ================================================
REM Step 3: Create Virtual Environment
REM ================================================
echo.
echo [INFO] [3/5] Creating Python virtual environment...

if exist ".venv" (
    echo [INFO] Virtual environment already exists
) else (
    echo [INFO] Creating virtual environment...
    uv venv --python 3.11 .venv
    if errorlevel 1 (
        echo [WARNING] Failed with Python 3.11, trying default...
        uv venv .venv
        if errorlevel 1 (
            echo [ERROR] Failed to create virtual environment
            exit /b 1
        )
    )
    echo [SUCCESS] Virtual environment created
)

REM ================================================
REM Step 4: Install Dependencies
REM ================================================
echo.
echo [INFO] [4/5] Installing dependencies...

REM Activate virtual environment
call .venv\Scripts\activate.bat

if exist "requirements.txt" (
    echo [INFO] Installing from requirements.txt...
    uv pip install -r requirements.txt
) else (
    echo [WARNING] requirements.txt not found
    echo [INFO] Installing common dependencies...
    uv pip install python-dotenv smolagents openai gradio pyyaml pandas openpyxl requests
)
echo [SUCCESS] Dependencies installed

REM ================================================
REM Step 5: Generate .env Configuration
REM ================================================
echo.
echo [INFO] [5/5] Generating configuration files...

if exist ".env" (
    echo [INFO] .env file already exists, overwriting
    echo [INFO] Backing up current configuration file to .env.backup
    copy .env .env.backup /Y >nul
)

REM Generate .env file
(
echo # ================================================
echo # AMS-IO-Agent Environment Configuration
echo # Auto-generated by setup_cmd.bat ^(Windows^)
echo # ================================================
echo.
echo # ================================================
echo # MODEL CONFIGURATION
echo # ================================================
echo # To add a model, configure these three variables:
echo #   MODELNAME_API_BASE=https://api.provider.com/v1
echo #   MODELNAME_MODEL_ID=model-id
echo #   MODELNAME_API_KEY=your_api_key_here
echo # Example: DeepSeek ^(default, uncomment to use^)
echo.
echo # DeepSeek
echo DEEPSEEK_API_BASE=https://api.deepseek.com/v1
echo DEEPSEEK_MODEL_ID=deepseek-chat
echo DEEPSEEK_API_KEY=your_deepseek_api_key_here
echo.
echo # Virtuoso Bridge Selection ^(true/1/yes to enable RAMIC Bridge, otherwise use skillbridge^)
echo USE_RAMIC_BRIDGE=true
echo.
echo # RAMIC Bridge Connection ^(only used when RAMIC Bridge is enabled^)
echo RB_HOST=127.0.0.1
echo RB_PORT=65432
echo.
echo # CDS Library Paths ^(Modify these paths according to your environment^)
echo CDS_LIB_PATH=%USERPROFILE%\TSMC28\TEST\cds.lib
echo CDS_LIB_PATH_180=%USERPROFILE%\TSMC180\TEST\cds.lib
echo.
echo # Logging Configuration
echo ENABLE_LOGGING=true
echo LOG_LEVEL=INFO
echo.
echo # User Profile Configuration
echo # Path to user profile markdown file ^(relative to project root^)
echo USER_PROFILE_PATH=user_data/default_user_profile.md
echo # Set to empty or 'none' to disable user profile loading
echo # USER_PROFILE_PATH=
) > .env

echo [SUCCESS] .env configuration file generated

REM Create necessary directories
if not exist "logs" mkdir logs
if not exist "user_data" mkdir user_data
if not exist "user_prompt" mkdir user_prompt

REM ================================================
REM Completion Summary
REM ================================================
echo.
echo =================================
echo   Setup Complete!
echo =================================
echo.
echo [SUCCESS] Configuration completed:
echo   [OK] Python virtual environment (.venv)
echo   [OK] Dependencies installed
echo   [OK] .env configuration file
echo   [OK] Required directories
echo.
echo Next Steps:
echo   1. Edit .env file and fill in your API keys
echo   2. Activate virtual environment:
echo      .venv\Scripts\activate.bat
echo   3. Run the application:
echo      python main.py
echo.
echo Note: Virtuoso integration is only available on Linux.
echo.

endlocal
